# https://taskfile.dev

version: '3'

vars:
  PGADMIN_COMPOSE: pgadmin/pgadmin-compose.yaml
  SUIPABASE_COMPOSE: supabase-project/docker-compose.yml
  AUTH_COMPOSE: supabase-project/auth-compose-providers.yml
  SUPABASE_ENV: supabase-project/.env
  COMPOSE_COMMAND: docker compose --env-file {{.SUPABASE_ENV}} -f {{.SUIPABASE_COMPOSE}} -f {{.AUTH_COMPOSE}} -f {{.PGADMIN_COMPOSE}} 

tasks:
  pull:
    cmds:
    - '{{.COMPOSE_COMMAND}} pull'
  up:
    cmds:
    - '{{.COMPOSE_COMMAND}} up -d'
  down:
    cmds:
    - '{{.COMPOSE_COMMAND}} down'
  logs_supa:
    cmds:
    - '{{.COMPOSE_COMMAND}} logs code'
  ps:
    cmds:
    - '{{.COMPOSE_COMMAND}} ps'
  pull_admin:
    cmds:
    - 'docker compose -f {{.PGADMIN_COMPOSE}} pull'
  up_admin:
    cmds:
    - 'docker compose -f {{.PGADMIN_COMPOSE}} up -d pgadmin' 
  down_admin:
    cmds:
    - 'docker compose -f {{.PGADMIN_COMPOSE}} down pgadmin'
  logs_admin:
    cmds:
    - 'docker compose -f {{.PGADMIN_COMPOSE}} logs pgadmin'
  ps_admin:
    cmds:
    - 'docker compose -f {{.PGADMIN_COMPOSE}} ps pgadmin'
  config_check:
    cmds:
    - '{{.COMPOSE_COMMAND}} config'
